### ISSUE TITLE
Node.jsのバージョン

### ISSUE THREAD

**Issue by sw-otay** [sw-kanekoi/kanekoi_training-nodejs#1]
Node.jsのバージョンはいくつですか？

**Comment by sw-kanekoi** [comment]
node : v22.11.0で実行しています。

**Comment by sw-otay** [comment]
承知しました！
安定版なので問題ないと思いますが、このバージョンを選んだ理由を教えていただけますか？

**Comment by sw-kanekoi** [comment]
最新のLTSなのでv22からインストールいたしました。

**Comment by sw-otay** [comment]
ありがとうございます！問題ないと思います。
